name: Feature Request
description: Suggest a new feature or enhancement.
title: "[FEATURE]: "
labels: enhancement
body:
  - type: markdown
    attributes:
      value: |
        We appreciate your idea! Please fill out the details below:

  - type: input
    attributes:
      label: Summary
      description: Provide a brief summary of the feature request.
      placeholder: "Add a dark mode to the interface."

  - type: textarea
    attributes:
      label: Description
      description: Provide a detailed description of the feature.
      placeholder: "Explain the purpose, who it benefits, and how it works."

  - type: textarea
    attributes:
      label: Benefits
      description: Explain why this feature would be useful.
      placeholder: "This will improve user experience by..."

  - type: textarea
    attributes:
      label: Potential Implementation
      description: If you have ideas on how it could be implemented, share them.
      placeholder: "Consider using [tool/library] to achieve this."
