name: Automated Project Status Workflow

on:
  issues:
    types: [opened, assigned, edited]
  pull_request:
    types: [opened, closed]

jobs:
  update-project-status:
    runs-on: ubuntu-latest

    steps:
      ### Step 1: Set Status to "Open" when an issue is created
      - name: Set Status to Open
        if: github.event.action == 'opened'
        env:
          PROJECT_ID: <your_project_id>
        run: |
          gh project item-field update ${{ env.PROJECT_ID }} --field "Status" --value "Open" --item-id ${{ github.event.issue.node_id }}

      ### Step 2: Update Status to "Todo" when issue is assigned
      - name: Set Status to Todo
        if: github.event.action == 'assigned'
        env:
          PROJECT_ID: <your_project_id>
        run: |
          gh project item-field update ${{ env.PROJECT_ID }} --field "Status" --value "Todo" --item-id ${{ github.event.issue.node_id }}

      ### Step 3: Update Status to "In-Progress" when a branch is linked
      - name: Set Status to In-Progress
        if: github.event.action == 'edited' && contains(github.event.issue.body, 'linked branch')
        env:
          PROJECT_ID: <your_project_id>
        run: |
          gh project item-field update ${{ env.PROJECT_ID }} --field "Status" --value "In-Progress" --item-id ${{ github.event.issue.node_id }}

      ### Step 4: Restrict transitions from "In-Progress"
      - name: Restrict Status Changes
        if: github.event.action == 'edited'
        run: |
          ALLOWED_STATUS="Blocked, Ready for QA, Todo"
          CURRENT_STATUS=$(gh project item-field get ${{ env.PROJECT_ID }} --field "Status" --item-id ${{ github.event.issue.node_id }})
          if [[ ! "$ALLOWED_STATUS" =~ "$CURRENT_STATUS" ]]; then
            echo "Invalid status transition from In-Progress to $CURRENT_STATUS"
            exit 1
          fi
