name: Automated Project Status Workflow

on:
  issues:
    types: [opened, assigned, edited]
  pull_request:
    types: [opened, closed]

jobs:
  update-project-status:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Install GitHub CLI
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      # Step 2: Authenticate GitHub CLI
      - name: Authenticate GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "${GH_TOKEN}" | gh auth login --with-token

      # Step 3: Set Status to "Open" when an issue is created
      - name: Set Status to Open
        if: github.event_name == 'issues' && github.event.action == 'opened'
        env:
          PROJECT_ID: PVT_kwHOC4nNZ84AwJjl
        run: |
          gh project item-field update $PROJECT_ID --field "Status" --value "Open" --item-id $(gh issue view ${{ github.event.issue.number }} --json id --jq .id)

      # Step 4: Update Status to "Todo" when issue is assigned
      - name: Set Status to Todo
        if: github.event_name == 'issues' && github.event.action == 'assigned'
        env:
          PROJECT_ID: PVT_kwHOC4nNZ84AwJjl
        run: |
          gh project item-field update $PROJECT_ID --field "Status" --value "Todo" --item-id $(gh issue view ${{ github.event.issue.number }} --json id --jq .id)

      # Step 5: Update Status to "In-Progress" when a branch is linked
      - name: Set Status to In-Progress
        if: github.event_name == 'issues' && github.event.action == 'edited' && contains(github.event.issue.body, 'linked branch')
        env:
          PROJECT_ID: PVT_kwHOC4nNZ84AwJjl
        run: |
          gh project item-field update $PROJECT_ID --field "Status" --value "In-Progress" --item-id $(gh issue view ${{ github.event.issue.number }} --json id --jq .id)

      # Step 6: Restrict transitions from "In-Progress"
      - name: Restrict Status Changes
        if: github.event_name == 'issues' && github.event.action == 'edited'
        env:
          PROJECT_ID: PVT_kwHOC4nNZ84AwJjl
        run: |
          ALLOWED_STATUS="Blocked, Ready for QA, Todo"
          CURRENT_STATUS=$(gh project item-field get $PROJECT_ID --field "Status" --item-id $(gh issue view ${{ github.event.issue.number }} --json id --jq .id) --jq .value)
          if [[ ! "$ALLOWED_STATUS" =~ "$CURRENT_STATUS" ]]; then
            echo "Invalid status transition from In-Progress to $CURRENT_STATUS"
            exit 1
          fi
