name: GitHub CLI Authentication Workflow

on:
  workflow_dispatch:

jobs:
  authenticate-gh-cli:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Install GitHub CLI
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      # Step 2: Clear Previous Authentication
      - name: Clear Previous Authentication
        run: |
          gh auth logout --hostname github.com || true

      # Step 3: Authenticate GitHub CLI
      - name: Authenticate GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "${GH_TOKEN}" | gh auth login --with-token
